language: generic
sudo: required
services:
  - docker

before_instal:
  - docker build -f Dockerfile.dev -t darcad/docker-react .

script:
  - docker run -e CI=true darcad/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-630277836218"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

  